### ISSUE TITLE
failure is name is empty

### ISSUE THREAD

**Issue by cdupont** [Happstack/happstack-authenticate#2]
happstack-authenticate fails correctly when provided with an empty name, but the message is strange:

```
Failed to decode JSON data.
```

The same happens with no password.

**Comment by stepcut** [comment]
I would suggest that it fails incorrectly.  The code likely would allow for an empty username except that a different bug is preventing the JSON from being decoded.

I am working on a patch that will allow developers to provide site-specific username, password, and email policies. This JSON bug should be fixed independently.

**Comment by stepcut** [comment]
Fixed in 86b11253551bbc904106c7e69925d5ac52056d4f

The angularjs client should now always submit valid JSON data.
