### ISSUE TITLE
Google OpenID in the demo does not work

### ISSUE THREAD

**Issue by billksun** [Happstack/happstack-authenticate#4]
The button for Google authentication seem to lead to a 404, I also noticed that on www.happstack.com, the same thing happens if you try to login via Google:

```
Happstack 7.4.6.1

Something went wrong here
Internal server error
Everything has stopped
```

`The error was "StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("Cache-Control","no-cache, no-store, max-age=0, must-revalidate"),("Pragma","no-cache"),("Expires","Fri, 01 Jan 1990 00:00:00 GMT"),("Date","Wed, 16 Mar 2016 16:26:14 GMT"),("Content-Type","text/html; charset=utf-8"),("Content-Encoding","gzip"),("X-Content-Type-Options","nosniff"),("X-XSS-Protection","1; mode=block"),("Server","GSE"),("Alternate-Protocol","443:quic,p=1"),("Alt-Svc","quic=\":443\"; ma=2592000; v=\"31,30,29,28,27,26,25\""),("Transfer-Encoding","chunked"),("X-Response-Body-Start","<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\"><title>Error 404 (Not Found)!!1</title><style>*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id=\"af-error-container\"><a href=//www.google.com/><span id=logo aria-label=Google></span></a><p><b>404.</b> <ins>That\226\128\153s an error.</ins><p>The requested URL was not found on this server. <ins>That\226\128\153s all we know.</ins></div>"),("X-Request-URL","GET https://www.google.com:443/accounts/o8/id")] (CJ {expose = []})"`

**Comment by stepcut** [comment]
Unfortunately, Google stopped supporting OpenID:

https://developers.google.com/identity/protocols/OpenID2Migration

So, we really just need to remove that option for happstack-authenticate.
