### ISSUE TITLE
happstack-authenticate 2.4.1.1 not uploaded to Hackage

### ISSUE THREAD

**Issue by tferrerm** [Happstack/happstack-authenticate#7]
Hi, the latest version of the package is missing in Hackage, so happstack-authenticate cannot be used with the latest version of happstack-server. As a workaround I tried cloning the repository and manually installing the package with cabal, but I somehow can't manage to force cabal to use the local package. Could you upload it?

**Comment by stepcut** [comment]
Done.

Many years ago I actually wrote a utility named 'hackage-whatsnew' which tells me if the directories on my local disk contain changes which are not yet on hackage. But it only helps if I actually run it :)

In other news -- I will be starting on `happstack-authenticate-3` next month, which will be a major rewrite. It should be able to migrate existing username/password accounts.

Alas, openid never really caught on, and google killed angular.

The new version will focus on just username/password, 2FA, and won't use angular.
